# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: VMOptions

steps:

  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: 'Resource Group'
      ConnectedServiceName: 'arm-deployments-cross-subscription'
      subscriptionName: '$(subscriptionId)'
      action: 'Create Or Update Resource Group'
      resourceGroupName: 'arm-deployment'
      location: 'East US 2'
      templateLocation: 'Linked artifact'
      csmFile: 'azuredeploy.json'
      csmParametersFile: 'azuredeploy.parameters.json'
      overrideParameters: '-adminUsername "$(vmUsername)" -adminPasswordOrKey "$(vmPassword)" -dnsLabelPrefix "$(vmDNSPrefix)"'
      deploymentMode: 'Incremental'
